server:
  servlet:
    context-path: /mdm-api

spring:
  application:
    name: mdm-api

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
    lazy: true
    timeout: 600000

logging:
  config: classpath:log4j2.xml