spring:
  application:
    name: mdm-api
  dubbo:
    application:
      name: ${spring.application.name}
    registry:
      address: nacos://mse-77279d20-p.nacos-ans.mse.aliyuncs.com:8848
    protocol:
      name: dubbo
    consumer:
      check: false
      lazy: true
      timeout: 600000
server:
  port: 10002
  servlet:
    context-path: /mdm