# 数据源配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://rm-wz95919qdqyonlbjn2o.mysql.rds.aliyuncs.com:3306/ehr_backend_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: pindao_test
      password: test@pindao
      max-active: 30

# dubbo 注册地址配置
dubbo:
  registry:
    address: nacos://mse-bdaddb10-nacos-ans.mse.aliyuncs.com:8848