server:
  port: 10001
  servlet:
    context-path: /mdm

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-wz95919qdqyonlbjn2o.mysql.rds.aliyuncs.com:3306/ehr_platform_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: ehr_platform
      password: ehr_platform
  dubbo:
    application:
      name: ehr-center-provider
      qos-enable: false
      qos-accept-foreign-ip: false
    protocol:
      name: dubbo
      port: 20880
    registry:
      address: nacos://mse-77279d20-p.nacos-ans.mse.aliyuncs.com:8848
    consumer:
      timeout: 4000

mybatis-plus:
  mapper-locations: classpath:mybatis-mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.pindao.infrabase.mdm.core.*.domain.model
  type-enums-package: com.pindao.infrabase.mdm.core.*.domain.enums
  global-config:
    #是否控制台 print mybatis-plus 的 LOGO
    banner: true
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
  configuration:
    call-setters-on-nulls: true
    #显示日志
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.pindao: debug